rvm:
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
env:
  - ISOLATED=true
  - ISOLATED=false
matrix:
  exclude:
- rvm: 1.9.3
  jdk: openjdk7
- rvm: 1.9.3
  jdk: oraclejdk7
